# Nome da Aplicação
spring.application.name=streaming-api

# Porta do Servidor (Padrão 8080)
server.port=8080

# Configurações do Banco de Dados H2 (Em Memória)
spring.datasource.url=${DB_URL:jdbc:h2:mem:streamdb}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}

# Habilitar o Console do H2 para visualização do banco
# Acesso via navegador: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Spring Data JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 'update' cria as tabelas automaticamente baseadas nas suas @Entity e as atualiza se houver mudanças
spring.jpa.hibernate.ddl-auto=update

# Exibir os comandos SQL no console (excelente para depuração e clean code)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true